apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-chat
  template:
    metadata:
      labels:
        app: backend-chat
    spec:
      containers:
        - name: backend-chat
          image: minwoo540/wak:backend-chat-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-chat
spec:
  type: LoadBalancer
  ports:
    - port: 8082
    - targetPort: 8080
  selector:
    app: backend-chat
