
spring:
  profiles:
    include: private
  config:
    import:
      - private/application-private.yml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

origin:
  frontend:
    http://localhost:3000 # todo set frontend origin
server:
  port: 8081