spring:
  profiles:
    include: private
  config:
    import:
      - private/application-private.yml
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
