stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: minwoo540/wak:backend-chat-latest
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  script:
    - docker build -t $DOCKER_IMAGE_NAME backend/chat/
    - docker push $DOCKER_IMAGE_NAME
