stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: minwoo540/wak:backend-chat-latest

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  script:
    - docker build -t $DOCKER_IMAGE_NAME backend/chat/
    - docker push $DOCKER_IMAGE_NAME
