apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-game
  template:
    metadata:
      labels:
        app: backend-game
    spec:
      containers:
        - name: backend-game
          image: minwoo540/wak:backend-game-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: backend-game
spec:
  type: LoadBalancer
  ports:
    - port: 8081
  selector:
    app: backend-game
